#%RAML 1.0 NamedExample
value:
  id: 100
  firstName: David
  lastName: Cooper
  address: San Fransisco
  postal: 55383
  country: USA
  miles: 180000
  createDate: 2016-02-28T16:41:41.090Z
  type: business