  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
  
file:
  workingDir: "F:/tmp/mule/file-connector/audit/resources/"
  outputDir: "output"